# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 741)
        MainWindow.setStyleSheet("\n"
"/* Apple-like Modern UI Theme */\n"
"\n"
"/* 전체 윈도우 배경 */\n"
"QMainWindow {\n"
"    background-color: #ececec;\n"
"}\n"
"\n"
"/* 타이틀 영역 라벨 */\n"
"#label_3 {\n"
"    font-size: 26px;\n"
"    font-weight: 700;\n"
"    color: #111111;\n"
"    background-color: transparent;\n"
"    padding: 12px;\n"
"    qproperty-alignment: AlignHCenter;\n"
"}\n"
"\n"
"/* 모든 라벨 */\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    color: #222222;\n"
"    background-color: #fafafa;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    border: 1px solid #e2e2e2;\n"
"}\n"
"\n"
"/* Input 텍스트 박스 */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    padding: 10px;\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* 버튼 */\n"
"QPushButton {\n"
"    background-color: #007aff;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    padding: 12px;\n"
"    border-radius: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #006ae6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0056c1;\n"
"}\n"
"\n"
"/* 리스트 메뉴 - 사이드바 */\n"
"QListWidget {\n"
"    background-color: #fafafa;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 16px;\n"
"    border: 1px solid #dcdcdc;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #007aff;\n"
"    color: white;\n"
"}\n"
"\n"
"/* 텍스트 박스들 */\n"
"QTextEdit, QTextBrowser {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 161, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_list = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.menu_list.setObjectName("menu_list")
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu_list.addItem(item)
        self.horizontalLayout.addWidget(self.menu_list)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 50, 631, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 641, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.poem_topic_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.poem_topic_input.setText("")
        self.poem_topic_input.setObjectName("poem_topic_input")
        self.verticalLayout_3.addWidget(self.poem_topic_input)
        self.poem_generate_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.poem_generate_btn.setObjectName("poem_generate_btn")
        self.verticalLayout_3.addWidget(self.poem_generate_btn)
        self.poem_result_view = QtWidgets.QTextBrowser(self.page)
        self.poem_result_view.setGeometry(QtCore.QRect(0, 150, 631, 361))
        self.poem_result_view.setObjectName("poem_result_view")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 641, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.image_prompt_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.image_prompt_input.setObjectName("image_prompt_input")
        self.verticalLayout_5.addWidget(self.image_prompt_input)
        self.image_generate_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.image_generate_btn.setObjectName("image_generate_btn")
        self.verticalLayout_5.addWidget(self.image_generate_btn)
        self.image_display_label = QtWidgets.QLabel(self.page_2)
        self.image_display_label.setGeometry(QtCore.QRect(0, 150, 639, 361))
        self.image_display_label.setText("")
        self.image_display_label.setScaledContents(True)
        self.image_display_label.setObjectName("image_display_label")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 641, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.translate_source_input = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.translate_source_input.setObjectName("translate_source_input")
        self.verticalLayout_4.addWidget(self.translate_source_input)
        self.translate_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.translate_btn.setObjectName("translate_btn")
        self.verticalLayout_4.addWidget(self.translate_btn)
        self.translate_result_view = QtWidgets.QTextEdit(self.page_3)
        self.translate_result_view.setGeometry(QtCore.QRect(0, 150, 631, 361))
        self.translate_result_view.setObjectName("translate_result_view")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 641, 301))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.audio_source_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.audio_source_input.setObjectName("audio_source_input")
        self.verticalLayout_6.addWidget(self.audio_source_input)
        self.audio_note_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.audio_note_btn.setObjectName("audio_note_btn")
        self.verticalLayout_6.addWidget(self.audio_note_btn)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 641, 301))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.file_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.file_input.setObjectName("file_input")
        self.verticalLayout_8.addWidget(self.file_input)
        self.user_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.user_input.setObjectName("user_input")
        self.verticalLayout_8.addWidget(self.user_input)
        self.file_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.file_btn.setObjectName("file_btn")
        self.verticalLayout_8.addWidget(self.file_btn)
        self.translate_result_view_2 = QtWidgets.QTextEdit(self.page_5)
        self.translate_result_view_2.setGeometry(QtCore.QRect(0, 300, 631, 361))
        self.translate_result_view_2.setObjectName("translate_result_view_2")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.page_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 641, 301))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.rudebot_input_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.rudebot_input_2.setText("")
        self.rudebot_input_2.setObjectName("rudebot_input_2")
        self.verticalLayout_9.addWidget(self.rudebot_input_2)
        self.rudebot_btn_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.rudebot_btn_2.setObjectName("rudebot_btn_2")
        self.verticalLayout_9.addWidget(self.rudebot_btn_2)
        self.translate_result_view_3 = QtWidgets.QTextEdit(self.page_6)
        self.translate_result_view_3.setGeometry(QtCore.QRect(0, 300, 631, 361))
        self.translate_result_view_3.setObjectName("translate_result_view_3")
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.menu_list.isSortingEnabled()
        self.menu_list.setSortingEnabled(False)
        item = self.menu_list.item(0)
        item.setText(_translate("MainWindow", "poem"))
        item = self.menu_list.item(1)
        item.setText(_translate("MainWindow", "image_maker"))
        item = self.menu_list.item(2)
        item.setText(_translate("MainWindow", "translation"))
        item = self.menu_list.item(3)
        item.setText(_translate("MainWindow", "tts"))
        item = self.menu_list.item(4)
        item.setText(_translate("MainWindow", "file_search"))
        item = self.menu_list.item(5)
        item.setText(_translate("MainWindow", "rudebot"))
        self.menu_list.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "시 주제를 입력하세요"))
        self.poem_generate_btn.setText(_translate("MainWindow", "시 생성"))
        self.label_2.setText(_translate("MainWindow", "생성할 그림을 설명해주세요"))
        self.image_generate_btn.setText(_translate("MainWindow", "그림 생성"))
        self.translate_btn.setText(_translate("MainWindow", "번역 실행"))
        self.label_4.setText(_translate("MainWindow", "오디오 파일의 경로를 입력하세요. "))
        self.audio_source_input.setText(_translate("MainWindow", "오디오 경로를 입력하세요"))
        self.audio_note_btn.setText(_translate("MainWindow", "오디오 회의 요약 노트 생성"))
        self.label_7.setText(_translate("MainWindow", "분석할 파일 경로를 입력하고, 파일에 관련된 질문을 작성해주세요."))
        self.file_input.setText(_translate("MainWindow", "파일 경로를 입력하세요"))
        self.user_input.setText(_translate("MainWindow", "파일 내에 질문사항을 입력해주세요"))
        self.file_btn.setText(_translate("MainWindow", "답변 생성"))
        self.label_8.setText(_translate("MainWindow", "봇에게 질문을 해주세요!"))
        self.rudebot_btn_2.setText(_translate("MainWindow", "답변 생성"))
        self.label_3.setText(_translate("MainWindow", "Open AI Projects"))
